hyphen:
  symbol: "-"
  name: マイナス記号、ハイフン
  tips:
    - "マイナス記号として: 減算の演算子。二項演算子として使われる場合（2-1など）と、単項演算子として使われる場合（-1など）がある"
    - "ハイフンとして: 一つの単語を複数の行に分けて書くとき、前の行の最後に置かれる"
    - "ハイフンとして: 英語で、複数の語から成る形容詞の、構成する語の間に置かれる（ten‐year‐old girlなど）"
    - "ハイフンとして: 電話番号や住所の数字部分などの区切りとして使われる"
    - 日本語入力時、長音（ー）の入力に用いられる
    - 長音（ー）は語尾に使われる（「私はあざみちゃんなのー。」など） 
    - よく使われる"-"はハイフンマイナスと呼ぶ
    - 「−」を変形させた￢は、否定を表す
    - 差集合の二項演算記号としても使われる。\（バックスラッシュ）を用いることもある
    - C言語などでは--をデクリメント演算子に使う
    - Wikiでは箇条書きに使う（--でもう1段階下の階層）
    - "HTMLなどでは&lt;!--と--&gt;で囲むとコメントアウトできる"
    - "Mathematicaで-&gt;はルールを表す（{x,x^2,a,b} /.x->3で{3,9,a,b}など）"
    - --や--------などいくつか並べて段落の区切りに使う（メールの署名など）
    - 全角の－（マイナス）、―（ダッシュ）、‐（ハイフン）、ー（長音）との違いに注意
    - 顔文字として口の部分や目の部分として使う（(-_-)、(^-^)など）

plus:
  symbol: "+"
  name: プラス記号
  tips:
    - 数学においての加算の演算子。二項演算子として使われる場合（2+1など）と、単項演算子として明示的に使われる場合（+1など）がある
    - 数学において論理和として使う場合もある
    - 「+」を円で囲んだ記号は、直和集合や排他的論理和に使われる
    - C言語などでは++をインクリメント演算子に使う
    - 文字列の連結にも使われる（"a" + "b" = "ab"など）
    - Wikiで番号付きリストを作るときに使う
    - Gmailなどではユーザー名の後に付ける+以降に任意の英数字を記して複数のメールアドレスとして利用できる（ユーザー名がhogeの場合、hoge+piyo@gmail.com など）
    - 顔文字として目の部分を表す（(+_+)など）

asterisk:
  symbol: "*"
  name: アスタリスク
  tips:
    - 多くのプログラミング言語では乗算に使う
    - 正規表現などでファイル名のワイルドカードとして使う（*.txtなど）
    - "押しボタン式電話機には、数字に加えて#と*のボタンが置かれ、特殊な用途に使われる"
    - Wikiでは見出しを作るときに使う（**でもう1段階下の階層）
    - C言語ではポインタを表す
    - C言語などでは"/*"と"*/"で囲むとコメントアウトになる
    - Mathematicaでは"(*"と"*)"で囲むとコメントアウトになる
    - 顔文字として目の部分を表す（(*_*)など）

slash:
  symbol: "/"
  name: スラッシュ
  tips:
    - 日付で、算用数字で表した月日または年月日を分ける。ただし、順序は国によって異なる（2010/11/22（→2010年11月22日）など）
    - 分数、あるいは、学術書などで通常は割り算を分数形式で書く文脈で、縦のスペースを節約したいときや、分数形式だと式が読みづらくなるときなど、「1/3」「a/b」のように書くことがある。ほとんどのプログラミング言語でも除算として用いる
    - UNIXオペレーティングシステムにおいて、パス区切り記号として、ディレクトリ（パーソナルコンピュータのフォルダと類似の概念）を表し、ディレクトリ名の後（ないし、ネットワーク内のコンピュータ名の後）に置かれる（Windowsにおける"\"と同等）
    - URLにおいてディレクトリーのパス区切り記号として使われる
    - "C言語などでは\"/*\"と\"*/\"で囲むとコメントアウトになる"
    - C言語やWikiなどでは//を使うと行末までコメントアウトになる
    - Mathematicaでは"引数//関数"で"関数[引数]"を示す（Pi//N(=3.14159)など）
    - "Mathematicaでf/@exprはMap関数を表し、exprの第1レベルにある各要素にfを適用する（f /@ {a,b,c,d,e}で{f[a],f[b],f[c],f[d],f[e]}など）"
    - "Mathematicaでは、expr/.rulesで式exprの下位区分のそれぞれを変換しようとするとき、規則または規則のリストを適用する（{x,x^2,y,z}/.x->aで{a,a^2,y,z}など）"
    - 顔文字として、手を挙げることを表す（(^-^)/など）

circumflex:
  symbol: "^"
  name: ハット記号、サーカムフレックス
  tips:
    - 元来はダイアクリティカルマークの一種
    - LaTeXなどで上付き文字を指定する記号
    - Excelなどでべき乗を示す演算子（Gnuplotなどでは**と書く）
    - C言語において「ビットごとの排他的論理和」の意味
    - ^^で笑顔を表す顔文字

backslash:
  symbol: "\\"
  name: 円記号、バックスラッシュ
  tips:
    - "円記号として: 日本の通貨単位の円や中国の人民元(Yuan)などを表す通貨記号である（¥1,980など）"
    - 円記号とバックスラッシュはキーが同じでシステムによって表示が異なるので問題視されている
    - "バックスラッシュとして: 集合論で差集合の演算子として使う"
    - Windowsのパスのディレクトリー名のパス区切り記号（"C:\hoge\piyo.txt"など）
    - LaTeXで命令を表す記号（\sectionなど）

atmark:
  symbol: "@"
  name: アットマーク
  tips:
    - 正式名称は単価記号
    - 元来は、単価を示すのに使われた
    - 電子メールのアドレスにおいて、個人名とドメイン名を分けるのに使われる（hoge@piyo.co.jpなど）
    -  Twitterではユーザーを指定するツイートでユーザー名の前に@を付ける（<a href="http://twitter.com/butchi_y">@butchi_y</a>など）
    - "Mathematicaでf@@exprは、式exprの頭部をfで置換する（f @@ {a,b,c,d}でf[a,b,c,d]など）"
    - "Mathematicaでf/@exprはMap関数を表し、exprの第1レベルにある各要素にfを適用する（f /@ {a,b,c,d,e}で{f[a],f[b],f[c],f[d],f[e]}など）"
    - 顔文字として目の部分を表す（(@_@)など）
    - 喪＠CェNｺ瑠ｦｭWｧ（「喪興瑠怒(ソーコールド)(仮)」）という曲がある

semicolon:
  symbol: ";"
  name: セミコロン
  tips:
    - 英語では、基本的に「強いコンマ( , )」ないし「弱い終止符( . )」である
    - 多くのプログラミング言語で命令の区切りに使われる
    - MATLABで配列内に新しい行が作成する（[5,8;3,4]など）
    - 汗を示す顔文字として使われる（(^_^;)など）

colon:
  symbol: ":"
  name: コロン
  tips:
    - 時刻や経過・所要時間を表す。時と分、分と秒を区切る（5:38（→5時38分）など）
    - 項目とその内容の間（日時: 3月3日 4時5分 など）
    - テレビ番組やDVDの字幕表示、チャットなどにおいて会話している人名とその内容を表す（A:ありがとうございます B:どういたしまして など）
    - 数学において比を表す（3:9=1:3など）
    - C言語などでの3項演算子で、if文におけるelseにあたる部分を示す（X>0?1:0など）
    - MATLABで数列を生成する（3:8で[3,4,5,6,7,8]、3:2:8で[3,5,7]など）
    - Wikiで定義リストを作るときに使う
    - MS-DOSおよびWindowsでは、ドライブレターの後に置かれる。(Cドライブ→C:)
    - "URLを記述する際にスキームの後に記述する。（http://butchi.jp/ , ftp: , mailto: など）"

comma:
  symbol: ","
  name: コンマ、読点
  tips:
    - 文の途中の区切りに打たれる点
    - 単語を並べるときにも使う（Aさん、Bさん、Cさんと食事をした）
    - 縦書きに用いる"、"と同等である
    - 全角"，"は論文などでよく使われる
    - 桁区切りに使う（1,980円など）
    - タグの区切り
    - CSVで列を区切るときに使う
    - Wikiで表組みを作るときに使う
    - 「藤岡弘、」という芸能人がいる

period:
  symbol: "."
  name: ピリオド、ドット、終止符、句点
  tips:
    - 文の終わりに打たれる点
    - 縦書きに用いる"。"と同等である
    - 全角"．"は論文などでよく使われる
    - 英語など多くの言語で、略語や略記語の最後に終止符と同じ点を打つ
    - 数学において小数点を意味する
    - 現在のフォルダーを示す（./index.htmlなど）
    - ..は、現在のフォルダーの親を示す（../index.htmlなど）
    - ファイル名（拡張子の前）やインターネットのホスト名（ドメイン名）やIPアドレスなどの区切り記号（readme.txt、butchi.jp、192.168.0.1など）
    - Mathematicaなどで、ベクトルや行列、テンソルの積を与える（\{a,b,c\}.\{x,y,z\}でa x+b y+c zなど）
    - Mathematicaでは、expr/.rulesで式exprの下位区分のそれぞれを変換しようとするとき、規則または規則のリストを適用する（{x,x^2,y,z}/.x->aで{a,a^2,y,z}など）
    - 顔文字では口の部分として用いられることがある（(^.^)など）
    - 「本田美奈子.」「KABA.ちゃん」という芸能人がいる
    - 「モーニング娘。」「ミニモニ。」というグループがある
    - 「ほっしゃん。 」「ハッピハッピー。」「なか。たつや」という芸能人がいる

space:
  symbol: " "
  name: スペース
  tips:
    - 語と語の区切りを表すために空ける空白
    - 姓と名の間にスペースを入れることがある。ミュージシャンの「大塚 愛」は姓と名の間に半角スペースを入れるのが正しい
    - 全角スペース"　"は段落のインデントなどに用いる
    - HTMLでは&amp;nbsp;（ノーブレークスペース）と書く
    - Wikiにおいて整形済みテキストを表す。行頭が半角空白で始まる行は整形済みテキストとなり、行の自動折り返しは行なわれない。

exclamation-mark:
  symbol: "!"
  name: 感嘆符
  tips:
    - エクスクラメーションマーク、雨垂れ、または俗にビックリマークとも呼ばれる
    - 視覚的な表現として、注意や危険であることを表現するために用いられる
    - 感嘆や命令など、普通よりも大きな声で発音される文の最後に、終止符に換えて置かれる
    - 数学では階乗を表す（3!=3×2×1=6など）
    - "!!は二重階乗と呼ばれる"
    - C言語などでは単独で否定を表し（!a（→aの論理否定）など）、!=で左辺と右辺が等しくないことを表す
    - HTMLなどでは<!--と-->で囲むとコメントアウトできる
    - 『けいおん!』という作品がある
    - 「もってけ!セーラーふく」「かえして!ニーソックス」という曲がある
    - 「ハロー!プロジェクト」という集団がある

question-mark:
  symbol: "?"
  name: 疑問符
  tips:
    - クエスチョンマーク、耳垂れ、はてなマーク、インテロゲーションマークとも呼ばれる
    - 携帯電話などで文字化けしたときに使われる
    - "C言語などでの3項演算子（条件判定）で、条件の終わりを示す（<code>X &gt; 0 ? 1 : 0</code>など）"
    - "phpでは、HTML構文と区別するためのデリミタに用いられる（<code>&lt;?php 本文 ?&gt;</code>）"

double-quotation:
 symbol: "\""
 name: 二重引用符
 tips:
   - 日本語の「」と同じ意味で使われることが多い
   - 様々な表記方法があり、“”を使う場合も多い
   - 多くのプログラミング言語では文字列を示す。JavaScriptなどの言語では'も同様の役割をすることが多い
   - HTMLでは&amp;quot;と書く
   - 濁音ﾞと似ている（IPデータ通信サービスに「エッジ」（H"）というものがある） 

single-quotation:
  symbol: "'"
  name: シングルクォーテーション、ダッシュ、引用符
  tips:
    - 英語では、音の省略に伴い文字を省略したことを表す
    - 類似の記号としてプライム（′）、アキュート・アクセント（´）などがあるが、それぞれ別のものである
    - ‘’を使う場合も多い
    - 分を表す記号として′が使われることもあるが、これは角度の単位の分にも用いられる
    - 数学では微分演算を示す（f'(x)など）
    - いくつかのプログラミング言語では文字列を示す。JavaScriptなどの言語では"も同様の役割をすることが多い
    - 顔文字として目の部分を表す（('3')など）

sharp:
  symbol: "#"
  name: シャープ、ナンバー、井桁
  tips:
    - "井桁として: 番号を示す数字の前に置かれる記号"
    - "シャープとして: 音楽で音を半音上げること、または上げた音、または楽譜上でそれを指示する記号"
    - "押しボタン式電話機には、数字に加えて#と*のボタンが置かれ、特殊な用途に使われる"
    - URIにおいてfragmentとその他の部分のセパレータに使われる。たとえばHTMLではページ内の（a要素のname属性やid属性で定義された）箇所を示すのに使う（http://butchi.jp/documents/planar_binary/index.html#quatenary_tile など）
    - "Mathematicaでは純関数に与えられる第1引数を示す（(3 + #) &[x]で3+xなど）"
    - Unixのシェルスクリプト、またそれが影響しているPerlやPythonなどのスクリプト言語や設定ファイル等で、行末までのコメントを表すのに使われる
    - メールなどでもコメントを書くときに使われる（全角＃の場合もある）
    - 「ベッキー♪♯」という歌手がいる
    - "顔文字として怒りマークとして使われることもある（゛(｀ヘ´#)など）"

dollar:
  symbol: $
  name: ドル記号
  tips:
    - ドルとペソの通貨記号（$2.00など）
    - 正規表現で、文字列の終わりを表す
    - BASICで、変数の後につけて文字列変数を表す
    - Perlで、変数の前に付けてスカラー変数を表す
    - PascalやDelphiで、定数の前に付けて16進定数を表す
    - phpで、定数の前に付けて変数を表す
    - シェルスクリプトで、環境変数を表す
    - 表計算ソフト「Microsoft Excel」で、セルの絶対参照（参照するセルの番号を固定させる指示。セル番号「B5」とした場合、行・列の移動や挿入によって相対的に番号が変化するが、「$B$5」では強制的に参照先のセル番号が「B5」に固定される）を表す
    - TeXでは、数式モードの区切りを示す

percent:
  symbol: "%"
  name: パーセント記号
  tips:
    - 割合を示す単位で、全体を百として示すものである
    - 同じような記号にパーミル記号 (‰) もあり、この記号は千分率を表し、1000 分の 1 を意味する
    - ほとんど見かけることはないが、10000 分の 1 を意味するパーミリアド記号（‱）も存在する
    - C言語などで剰余の演算子として使用する（8%3で2（8を3で割ったときの余り）など）
    - C言語などの書式付入出力関数（printf など）では書式指定を示す。たとえば、%dで整数、%cで 1 文字などの出力となる
    - MATLABにおいて、%{および%}の記号で囲むと1行以上のコメントアウトができる
    - LaTeXやMATLABなどで行末までのコメントアウトとして使う
    - Wikiでは、行中のインライン要素を%%ではさむと、インライン要素に取消線が付く
    - MS-DOSやMicrosoft Windowsなどでは、標準のコマンドラインインタプリタにおいて環境変数を表す記号として使用されている（echo %PATH% など）

ampersand:
  symbol: "&"
  name: アンド、アンパサンド
  tips:
    - 「〜と…」を意味する記号
    - 英語の "and" に相当するラテン語の "et" の合字
    - C言語などで&&は論理ANDを表し（1&&1（→1）など）、&はビットANDを表す（0x12345678 & 0x0f0f0f0f（→0x02040608）など）
    - HTMLでは&amp;amp;と書く
    - LaTeXでは表組みの列を区切る記号として使われる（国名 & 人口(百万人) & 首都 \\日本 & 120 & 東京 \\ など）
    - BASIC 系列の言語では文字列の連結演算子として使用される（"foo"&"bar"（→"foobar"）など）
    - "Mathematicaでは純関数の終わりを示す（(3 + #)&[x]で3+xなど）"

equal:
  symbol: "="
  name: イコール、等号
  tips:
    - ハールーン・アッ＝ラシード (Hārūn al-Rashīd) のように名前の読みがリエゾンする場合に「＝」を用いる事もあるが、正しくはこれは「゠」のダブルハイフンを使用するのが正しい
    - 等号の左右が等価であることを表す
    - ほぼ等しいことを示す記号として「∼」「≃」「≈」「≒」がある
    - 似た記号に合同記号≡がある
    - 等しくないということを示す記号として等号否定≠がある
    - ある記号Aが意味するものを、ある記号Bが意味するものと同じであると定義するには、「:=」を用いて「A:=B」と書く。このほかにも、「＝」の上に小さく"def"や"△"などを書いた記号が用いられることともある
    - 多くのプログラム言語では、「=」は右辺の値を左辺の変数へ代入することを表す代入演算子である
    - 多くのプログラミング言語では、数学での「=」に当たる等価演算子（多くの場合、比較演算子の一種とされる）は「=」を2つ続けた「==」（ダブルイコール）である
    - プログラミング言語では、「≠」にあたる不等価演算子には、「!=」（等価演算子に「==」を使う言語の多く）、「<>」（等価演算子に「=」を使う言語の多く）、「/=」、「^=」などが使われる
    - C言語、perl、Javaなどでは、通常の代入演算子以外に、加算代入演算子「+=」、減算代入演算子「-=」、乗算代入演算子「*=」、除算代入演算子「/=」などを備える（「a」が変数のとき、「a += 5;」は「a = a + 5;」と同じ など）
    - 異なる意味合いの比較に、別の演算子を用意している言語もある。たとえばPerlでは「==」「!=」は数値としての比較、「eq」「ne」は文字列としての比較をする演算子である
    - 顔文字として眠い時などの目の部分に使われる（(=_=)など）
    - 『らき☆すた』の泉こなたを表す顔文字として使われる（(＝ω＝．)、(≡ω≡．)）

tilde:
  symbol: ~
  name: チルダ
  tips:
    - 鼻音に関する音をあらわすダイアクリティカルマークの一種として使われる
    - UNIX系オペレーティングシステムでは、チルダはホームディレクトリを表す文字として用いられる（“~”単体で自身のホームディレクトリ、“~ユーザ名”でそのユーザのホームディレクトリ）
    - URLではしばしばユーザ別ホームディレクトリを表す記号として用いられる（http://merl.ec.t.kanazawa-u.ac.jp/~iwabuchi/ など）
    - C言語、およびそれに影響を受けた言語の多くでは、ビットごとのNOTを取る単項演算子として定義されている
    - Perlなどいくつかの言語においては、正規表現マッチングを行う =~  演算子と、その否定として !~ 演算子が用意されている
    - Wikiで段落を明示するときに使う
    - 「Jｪﾁ~ｯじo™ｳ」（「同じ夜」）という曲がある

vertical-bar:
  symbol: "|"
  name: 縦線、バーティカルバー
  tips:
    - バーティカルバーの中央が切断されている記号はブロークンバー（英語:Broken bar）といい、「¦」と書き表せる
    - "数学において|x|の形で、絶対値の記号として用いる"
    - "数学において{x|x<2}の形で、定義を表す"
    - UNIXやMS-DOSではパイプの記号として用いる
    - "SQLではバーティカルバーを二つ合わせることにより(||)文字列の連結を意味する"
    - "C言語などの多くのプログラム言語では、単なる論理和は「||」、ビット単位の論理和は「|」 で表される"
    - Wikiで表組みを作るときに使う

grave-accent:
  symbol: "`"
  name: グレイヴ・アクセント
  tips:
    - フランス語、カタルーニャ語、イタリア語、ベトナム語などのラテン文字を用いる言語の表記に用いられるアクセント符号で、ダイアクリティカルマークの一種
    - 重アクセント、低アクセントなどとも
    - いくつかのシェルスクリプトやperlなどでは、`……` と文字列を囲むと、文字列をコマンドとして実行し、実行結果の標準出力を文字列として返す
    - LaTeXにおいて開き引用符を``、閉じ引用符''として用いる
    - Mathematicaでパッケージを読み込むときに使う（"<< DiscreteMath`CombinatorialFunctions`"など）

gt:
  symbol: ">, <"
  name: 大なり、小なり、不等号
  tips:
    - 実数などの大小を表すための数学記号である
    - 複号同順を使った式で「≶」「≷」「≦」「≧」もしくは「≶」「≷」「⋚」「⋛」「≤」「≥」「⋜」「⋝」などの記号がある
    - 比が極度に大きいことを示すために、通常の不等号ではなく、「≪」「≫」が使用される
    - 「≲」は「小さいかほぼ等しい」、「≳」は「大きいかほぼ等しい」を意味する。近似計算で使われる
    - ほとんどの言語で、等号付き不等号は 
    - Pascal、SQLなどでは、<> が否定等号（≠）として使われる
    - Perlでは、
    - ">はメールやコメント、Wikiで引用やコメント先を表すときに使う（「>Butchiさん 例の件お願いします」など）"
    - "プログラミング言語で括弧としても使われる（\"#include <stdio.h>\"など）"
    - XMLやHTMLなどのSGML言語では、
    - "HTMLでは&amp;gt;、&amp;lt;と書く"
    - C言語などにおいて<<と>>はビットシフトを表す
    - C++では<<と>>はストリーム入出力も表す
    - "Mathematicaで->はルールを表す（{x,x^2,a,b} /.x->3で{3,9,a,b}など）"
    - Mathematicaでパッケージを読み込むときに使う（"<< DiscreteMath`CombinatorialFunctions`"など）

underscore:
  symbol: "_"
  name: アンダースコア
  tips:
    - アンダーバーは和製英語である
    - JIS X 0201では「アンダライン」となっている
    - インターネットのURLやメールアドレスのようなスペースが使えないところで、かわりにアンダースコアを置くことが行われる。ただし、それらのうちドメイン名部分にはアンダースコアを用いることはできず、用いることができるのはハイフンマイナスである
    - 顔文字として口の部分を表すときに使われる（(=_=)など）

round-bracket:
  symbol: "()"
  name: 括弧、丸括弧
  tips:
    - 小説等の文学作品では、会話に表れない心中表現であることを示すのに用いることがある
    - 数式においては、式をグループ化して演算の優先順位の明示・変更を行うときに用いる。プログラミング言語でも同様の用途で使用する言語が多い
    - 幾何学で座標を示す場合に1座標の定義を示す（(x,y)=(1,2)など）
    - 数学やプログラミング言語で、関数の引数を明示するのに用いる
    - 数学の区間において、開いていることを示す（[0,1)など）
    - Mathematicaでは"(*"と"*)"で囲むとコメントアウトになる
    - 顔文字として顔の輪郭を表すときに使われる（(^-^)など）
    - Wikiでは、行中でインライン要素を (( と )) ではさむと、注釈が作成され、行中に注釈へのリンクが貼られる
    - BASICなどの一部のプログラミング言語やスクリプト言語では配列の要素を指定するのにも用いる

square-bracket:
  symbol: "[]"
  name: 角括弧
  tips:
    - 数式においては、丸括弧()を入れ子にする場合に外側の括弧を角括弧とするほか、丸括弧の代わりに角括弧を用いる様式もある
    - 数学の区間において、閉じていることを示す（[0,1)など）
    - Webサービスなどでタグを記すときに使う
    - Wikiではリンクを貼るときに[[と]]を使う（[[エイリアス名:http://www.example.com/]]など）
    - LaTeXで\[と\]で囲まれた部分は数式として扱われる
    - Mathematicaで関数の引数を入れる部分に使う（f[x]など）
    - Mathematicaで[[と]]を使ってリストの要素を指定する（{5,3,8}[[2]](=3)など）

curly-bracket:
  symbol: "{}"
  name: 波括弧
  tips:
    - ブレース・ブレイス (brace) およびカーリーブラケット(curly bracket)・カール (curl)とも言う
    - 数式においては、角括弧 [] を入れ子にするときに外側の括弧を波括弧とする
    - 数学において集合を定義するときに使う（{x|xは3の倍数と10進法で3が付く数}など）
    - C言語を始めとした多くのプログラミング言語やスクリプト言語では関数やif文・for文などの構文・命令等や変数のローカルスコープを表現する（if(x

japanese-style-quotation-marks:
  symbol: "「」"
  name: 鉤括弧
  tips:
    - 題目（題名・表題・外題・箇条・主題・問題・名目）などを特に提示する場合に用いる
    - 「いわゆる」「いわば」という、言葉を文字通りに受け取ってはいけないということを示す際に用いる。鉤括弧を付けた相手に、「相手はそう自称しているが、自分は認めない」という意思表示になる
    - 似た記号として二重鉤括弧『』がある
    - ある作品が複数の作品から成り立っている場合、個々の作品の名称に鉤括弧「」を、作品全体ないし作品集の名称に二重鉤括弧『』を、それぞれ用いる（アルバム『A Journey To Freedom』から「My Favorite Swing」をお聞きください。など）

black-lenticular-bracket:
  symbol: "【】"
  name: 隅付き括弧
  tips:
    - 隅付きパーレン（すみつきパーレン）・太亀甲（ふときっこう）・黒亀甲（くろきっこう）・墨付き括弧（すみつきかっこ）とも言う
    - タイトルの最初と最後に付けてアピールポイントを強調する（「【痩せ過ぎ】BMI24当たりが最も長生き【注意】」など）。2ちゃんねるやニコニコ動画のタイトルなどで散見される

em-tilde:
  symbol: "～"
  name: 全角チルダ、波線、波ダッシュ
  tips:
    - "波ダッシュは、範囲を表すために用いられる<ul><li>場所に対して: 東京〜大阪</li><li>時間に対して: 5時〜6時</li><li>数量に対して: 100人〜150人</li></ul>"
    - 副題を示すときに使われる（「空間スペクトルを用いたジャギー評価に関する一考察〜擬似的不規則画素配置によるジャギーの解消効果〜」など）
    - 「〜する」「〜からの」のように前に記載されている言葉を省略する場合や、「寿限無寿限無〜」のように後ろが長いために省略する場合などに使う
    - 表示システムによっては波が反転している場合もある
    - 長音（ー）の砕けた使い方（「へ～。」など）で、これと同じようなものに「〰」などがある
    - 顔文字として口の部分を表すときに使われる（(^～^)など）

point:
  symbol: "・"
  name: 中黒
  tips:
    - 中ぽつ、中ポツ（なかぽつ）、中ぽち、中点（なかてん）、中テン、黒丸なども呼ばれる
    - 箇条書き（ただしこの場合はビュレットという）
    - 乗算
    - 顔文字として目の部分を表すときに使われる（(`・ω・´)など）

dotted-line:
  symbol: "…"
  name: 三点リーダー
  tips:
    - 省略を示す
    - あまりのあるわり算の「あまり」（14÷3＝4…2など）

iteration-mark:
  symbol: "々、ヽ、ゝ"
  name: 踊り字
  tips:
    - 同じ字の繰り返しを表す約物である
    - おどり、繰り返し符号（くりかえしふごう）、重ね字（かさねじ）、送り字（おくりじ）、揺すり字（ゆすりじ）、重字（じゅうじ）、重点（じゅうてん）、畳字（じょうじ）などとも呼ぶ

ditto:
  symbol: 〃
  name: ノノ字点、同じく記号
  tips:
    - 表などで上または左の内容と同一の場合の省略文字として使用される約物のひとつである

degree:
  symbol: °
  name: ど、デグリー
  tips:
    - 角度の単位の度に使われる。
    - 温度の単位の度に使われる。単独ではなく、次のようにラテン文字1〜2文字と組み合わせて使う（℃など）
    - 半濁音（ﾟ）と似ている
    - 顔文字として目の部分を表すときに使われる（(°д°)など）

arrow:
  symbol: "←、↑、→、↓"
  name: 矢印
  tips:
    - ←は直前の文の説明に用いる
    - ↑は1つ上の文の説明に用いる
    - →は直前の文から導出されることを示す
    - ↓は1つ上の文から導出されることを示す
    - Mathematicaで→はルールを表す（{x,x^2,a,b} /.x→3で{3,9,a,b}など）。->と同様である
    - 「まっがーれ↓スペクタクル」という曲がある


bullets-symbol:
  symbol: ●○■□◆◇★☆▲△▼▽
  name: 箇条書き記号
  tips:
    - 箇条書き記号として行頭に用いられる
    - ★、☆はお茶目な感じを出すために文末に使われることがある（やったね☆ など）
    - ◆は2chにおいてトリップを示す記号。（「ほげ◆Ig9vRBfuyA」など）
    - 一部の文書処理ソフトでは■、□などを箇条書き記号として使うことができる
    - 「つのだ☆ひろ」という芸能人がいる
    - 「漫☆画太郎」という漫画家がいる
    - 長島☆自演乙☆雄一郎というキックボクサーがいる
    - 『らき☆すた』という作品がある
    - 「まほろば○△」（まほろばまるやま）という曲がある

note:
  symbol: "♪、♫、♬、♩"
  name: 音符
  tips:
    - 文末に使われ、気分の高揚を表す（「ラッキー♪」など）
    - 「みくみくにしてあげる♪【してやんよ】」という曲がある
    - 「ベッキー♪♯」という歌手がいる

cross:
  symbol: "×"
  name: かける、ばつ
  tips:
    - 他の読み方として、「ぺけ」「ばってん」「ちょめ」「クロス」「バイ」など
    - 筆記時の乗算（主に初等教育）
    - クロス積（ベクトル積）
    - バツ

x:
  symbol: "x"
  name: エックス
  tips:
    - 乗算
    - XXXでキス

two:
  symbol: "2"
  name: に
  tips:
    - 英語のtoの意味
    - 変換ツールの名前として使われることが多い（LaTeX2HTMLなど）

four:
  symbol: "4"
  name: よん
  tips:
    - 英語のforの意味
    - ソフトウェアの名前に使われる場合がある（TeX4htなど）

any:
  symbol: "∀"
  name: 全称記号
  tips:
    - 全称記号。数理論理学において「すべての」（全称量化）を表す記号である
    - 顔文字として、口を表す（（・∀・）ｲｲ！ など）

exist:
  symbol: "∃"
  name: 存在記号
  tips:
    - 存在記号。数理論理学（特に述語論理）において、少なくとも1つのメンバーが述語の特性や関係を満たすことを表す記号である
    - 数理論理学において∃!で唯一つ存在することを表すことがある

therefore-sign:
  symbol: "∴、∵"
  name: ゆえに、なぜならば
  tips:
    - 「∴」は「ゆえに」、又は「すなわち」と読み、数学などでそれまでの内容から誘導できる結論に使用される学術記号である
    - 「∵」は「なぜならば」と読み、数学などでそれまでの内容から誘導できる結論に使用される学術記号である

vertical-symbol:
  symbol: "⊥"
  name: 垂直記号
  tips:
    - 垂直記号。幾何学で用いられる記号である。下線の中央上に接する縦線を引く図形を書く。垂直記号の前後が垂直であることを示す

corner-symbol:
  symbol: "∠"
  name: 角記号
  tips:
    - 角記号。幾何学で用いられる記号である。下線の左に接し、右上方向に伸びる斜線を引く図形を書く

right-angle-symbol:
  symbol: "∟"
  name: 直角記号
  tips:
    - 直角記号。幾何学で用いられる記号である。下線の左に接する縦線を引く図形を書く。角を表す角記号「∠」の直角の場合に用いられる記号である

latin-d:
  symbol: "д、Д"
  name: デー
  tips:
    - 顔文字として、口を表す（(゜Д゜)ウマー など）

infinity:
  symbol: "∞"
  name: 無限大
  tips:
    - 数学において無限大を表す
    - 「関ジャニ∞」（かんじゃにエイト）というグループが存在する

paragraph-mark:
  symbol: "¶"
  name: 段落記号
  tips:
    - 段落記号。段落を表す約物である。一般には、段落の区切りを表す目的で、段落の始めあるいは段落の終りのいずれか一方に置かれる
    - 図形はラテン文字の「C」にスラッシュを書いた字形が元になっている

parallel-to:
  symbol: "‖、∥"
  name: 双柱、平行記号
  tips:
    - 「‖」は双柱と呼ばれる。縦線であるバーティカルバーを横に2つ並べた記号である。文字列の区切りで使用されるほか、発音記号や数学においても使用される
    - 「∥」は平行記号と呼ばれる。平行記号の前後の線あるいは面などが平行であることを示す。日本では、一般に「//」のかたちで表記するが、欧米では「||」のかたちで表記することが多い
    - 平行の否定を表す記号は「∦」である。日本では、一般に「//」に「＼」を重ねた図形で表記されるが、欧米では「||」に「／」を重ねた図形で表記する
    - 文字化けで||で表示されるシステムと//と表示されるシステムがある

v:
  symbol: "v"
  name: ブイ
  tips:
    - ハートを表す

w:
  symbol: ｗ
  name: 草、ダブル
  tips:
    - （笑）の略。ニコニコ動画などで笑いを表すときに使う（「きめぇｗｗｗｗ」など）
